[general]
live_config_reload = true
working_directory = "None"

# Dracula Pro
import = ["~/.config/alacritty/themes/dracula-pro-van-helsing.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 5 }
decorations = "Buttonless"
dynamic_padding = true
# opacity = 0.9
# blur = true

[font]
size = 16

# normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
# bold = { family = "SauceCodePro Nerd Font Mono", style = "Bold" }
# italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "SauceCodePro Nerd Font Mono", style = "Bold Italic" }

normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

[terminal]
shell = { program = "/bin/zsh", args = ["--login"] }

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]
