"$schema" = 'https://starship.rs/config-schema.json'

### STARSHIP ###

add_newline = true

[character]
success_symbol = "[ #](bold green)"
error_symbol = "[ *](bold red)"
vimcmd_symbol = "[ V](bold purple)"

[hostname]
format = "[$hostname]($style) in "
style = "bold red"
trim_at = "-"
ssh_only = true

[status]
symbol = '!'
format = ' [$symbol]($style)'
map_symbol = true
disabled = false

[username]
style_user = "bold blue"
style_root = "bold red"
format = " [$user]($style) in "
show_always = true


### OTHER ###

[aws]
disabled = true

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[swift]
disabled = true
