# GIT
[[mgr.prepend_keymap]]
on = ["g", "G"]
run = "plugin vcs-files"
desc = "Show Git file changes"

# MACTAG
[[mgr.prepend_keymap]]
on = ["b", "a"]
run = "plugin mactag add"
desc = "Tag selected files"

[[mgr.prepend_keymap]]
on = ["b", "r"]
run = "plugin mactag remove"
desc = "Untag selected files"

# YAZI
[[mgr.prepend_keymap]]
on = ["g", "C"]
run = "cd ~/Code"
desc = "Go to ~/Code"

[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/.config"
desc = "Go to ~/.config"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Documents"
desc = "Go to ~/Documents"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Go to ~/Downloads"

[[mgr.prepend_keymap]]
on = ["g", "e"]
run = "cd ~/.config/nvim"
desc = "Go to nvim config"

[[mgr.prepend_keymap]]
on = ["d", "d"]
run = "yank --cut"
desc = "Cut selection"

[[mgr.prepend_keymap]]
on = ["y", "y"]
run = "yank"
desc = "Yank selection"

[[mgr.prepend_keymap]]
on = ["d", "D"]
run = "remove"
desc = "Move selection to trash"

[[mgr.prepend_keymap]]
on = ["m", "d"]
run = "create --dir"
desc = "Move selection to trash"

[[mgr.prepend_keymap]]
on = ["A"]
run = "rename"
desc = "Move selection to trash"
