# GIT
[[mgr.prepend_keymap]]
on   = [ "g", "G" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

# MACTAG
[[mgr.prepend_keymap]]
on   = [ "b", "a" ]
run  = "plugin mactag add"
desc = "Tag selected files"

[[mgr.prepend_keymap]]
on   = [ "b", "r" ]
run  = "plugin mactag remove"
desc = "Untag selected files"
