"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

### YAZI ###

[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_translit = true
show_hidden = true
# linemode = "custom_linemode"

##### PLUGINS #####

### FETCHERS ###
# GIT
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

# MACTAG
[[plugin.prepend_fetchers]]
id = "mactag"
name = "*"
run = "mactag"

[[plugin.prepend_fetchers]]
id = "mactag"
name = "*/"
run = "mactag"

### PREVIEWERS ###

# RICH-CLI
[[plugin.prepend_previewers]]
name = "*.csv"
run = 'rich-preview'

[[plugin.prepend_previewers]]
name = "*.md"
run = 'rich-preview'

[[plugin.prepend_previewers]]
name = "*.rst"
run = 'rich-preview'

[[plugin.prepend_previewers]]
name = "*.ipynb"
run = 'rich-preview'

[[plugin.prepend_previewers]]
name = "*.json"
run = 'rich-preview'

# PIPER
[[plugin.prepend_previewers]]
name = "*.tar*"
run = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
name = "*.csv"
run = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
name = "*.md"
run = 'piper -- rich -j --left --panel=rounded --guides --line-numbers --force-terminal "$1"'

[[plugin.append_previewers]]
name = "*"
run = 'piper -- hexyl --border=none --terminal-width=$w "$1"'
