-- Shows configured keymaps on the fly
-- https://github.com/folke/which-key.nvim

return {
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
      delay = 0,
      icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
          Up = '<Up> ',
          Down = '<Down> ',
          Left = '<Left> ',
          Right = '<Right> ',
          C = '<C-…> ',
          M = '<M-…> ',
          D = '<D-…> ',
          S = '<S-…> ',
          CR = '<CR> ',
          Esc = '<Esc> ',
          ScrollWheelDown = '<ScrollWheelDown> ',
          ScrollWheelUp = '<ScrollWheelUp> ',
          NL = '<NL> ',
          BS = '<BS> ',
          Space = '<Space> ',
          Tab = '<Tab> ',
          F1 = '<F1>',
          F2 = '<F2>',
          F3 = '<F3>',
          F4 = '<F4>',
          F5 = '<F5>',
          F6 = '<F6>',
          F7 = '<F7>',
          F8 = '<F8>',
          F9 = '<F9>',
          F10 = '<F10>',
          F11 = '<F11>',
          F12 = '<F12>',
        },
      },

      spec = {
        { '<leader>s', group = '[S]earch' },
        { '<leader>t', group = '[T]oggle' },
        { '<leader>h', group = '[H]unk', mode = { 'n', 'v' } },
        { '<leader>w', group = '[W]indow', mode = { 'n' } },
        { '<leader>o', group = '[O]pen', mode = { 'n' } },
        { '<leader>g', group = '[G]it', mode = { 'n' } },
        { '<leader>t', group = '[T]oggle', mode = { 'n' } },
        { '<leader>c', group = '[C]ode', mode = { 'n' } },
        { '<leader>f', group = '[F]iles', mode = { 'n' } },
        { '<leader>b', group = '[B]uffers', mode = { 'n' } },
        { '<leader>d', group = '[D]ebug', mode = { 'n' } },
        { '<leader>u', group = '[U]tils', mode = { 'n' } },
      },
    },
  }
